Fixed a error in test_create_tenant_rpc
In the latest version of oslo_messaing/server.py, an error has occurred
such as the following.

     File "/opt/stack/networking-nec-newton-fix-errors/.tox/py27/local/lib/python2.7/site-packages/oslo_messaging/server.py", line 348, in __init__
        super(MessageHandlingServer, self).__init__()
    TypeError: must be type, not MagicMock

Then, the mock patch of MessageHandlingServer was changed to ServiceBase
which is a parent class of MessageHandlingServer.

Change-Id: Ib8ef818aea5a7c64e3177866d2895da91e5de2bb